# Generated by Django 2.2.6 on 2019-10-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopList_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='newlist',
            name='item',
        ),
        migrations.AddField(
            model_name='newlist',
            name='new_list',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
