# Generated by Django 2.2.6 on 2019-10-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopList_app', '0002_auto_20191013_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_list', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewList',
        ),
    ]
