# Generated by Django 2.2.6 on 2019-10-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopList_app', '0003_auto_20191014_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='new_list',
            new_name='list_name',
        ),
    ]
